import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <Link href="/">홈화면</Link>
          <Link href="/api/apply">API GET 요청</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
